export const partidos = [
  {
    "id": 1,
    "grupo": "A",
    "local": "Al Ahly",
    "visitante": "Inter Miami",
    "fecha": "0",
    "hora": "-",
    "ciudad": "0",
    "escudoLocal": "./img/escudos/alahly.webp",
    "escudoVisitante": "./img/escudos/intermiami.webp"
  },
  {
    "id": 2,
    "grupo": "B",
    "local": "PSG",
    "visitante": "Atlético de Madrid",
    "fecha": "15 junio",
    "hora": "12:00",
    "ciudad": "Los Ángeles",
    "escudoLocal": "./img/escudos/psg.webp",
    "escudoVisitante": "./img/escudos/atleticomadrid.webp"
  },
  {
    "id": 3,
    "grupo": "C",
    "local": "Bayern Múnich",
    "visitante": "Auckland City",
    "fecha": "10",
    "hora": "-",
    "ciudad": "0",
    "escudoLocal": "./img/escudos/bayern.webp",
    "escudoVisitante": "./img/escudos/aucklandcity.webp"
  },
  {
    "id": 4,
    "grupo": "A",
    "local": "Palmeiras",
    "visitante": "Oporto",
    "fecha": "15 junio",
    "hora": "18:00",
    "ciudad": "Nueva York-Nueva Jersey",
    "escudoLocal": "./img/escudos/palmeiras.webp",
    "escudoVisitante": "./img/escudos/porto.webp"
  },
  {
    "id": 5,
    "grupo": "B",
    "local": "Botafogo",
    "visitante": "Seattle Sounders",
    "fecha": "15 junio",
    "hora": "19:00",
    "ciudad": "Seattle",
    "escudoLocal": "./img/escudos/botafogo.webp",
    "escudoVisitante": "./img/escudos/seattle.webp"
  },
  {
    "id": 6,
    "grupo": "D",
    "local": "Chelsea",
    "visitante": "León",
    "fecha": "16 junio",
    "hora": "15:00",
    "ciudad": "Atlanta",
    "escudoLocal": "./img/escudos/chelsea.webp",
    "escudoVisitante": "./img/escudos/leon.webp"
  },
  {
    "id": 7,
    "grupo": "C",
    "local": "Boca Júniors",
    "visitante": "Benfica",
    "fecha": "16 junio",
    "hora": "18:00",
    "ciudad": "Miami",
    "escudoLocal": "./img/escudos/boca.webp",
    "escudoVisitante": "./img/escudos/benfica.webp"
  },
  {
    "id": 8,
    "grupo": "D",
    "local": "Flamengo",
    "visitante": "Esperance Sportive",
    "fecha": "16 junio",
    "hora": "21:00",
    "ciudad": "Filadelfia",
    "escudoLocal": "./img/escudos/flamengo.webp",
    "escudoVisitante": "./img/escudos/esperance.webp"
  },
  {
    "id": 9,
    "grupo": "E",
    "local": "River Plate",
    "visitante": "Urawa Red Diamonds",
    "fecha": "17 junio",
    "hora": "12:00",
    "ciudad": "Seattle",
    "escudoLocal": "./img/escudos/river.webp",
    "escudoVisitante": "./img/escudos/urawa.webp"
  },
  {
    "id": 10,
    "grupo": "F",
    "local": "Fluminense",
    "visitante": "Borussia Dortmund",
    "fecha": "17 junio",
    "hora": "12:00",
    "ciudad": "Nueva York-Nueva Jersey",
    "escudoLocal": "./img/escudos/fluminense.webp",
    "escudoVisitante": "./img/escudos/borussia.webp"
  },
  {
    "id": 11,
    "grupo": "E",
    "local": "Monterrey",
    "visitante": "Inter de Milán",
    "fecha": "17 junio",
    "hora": "18:00",
    "ciudad": "Los Ángeles",
    "escudoLocal": "./img/escudos/monterrey.webp",
    "escudoVisitante": "./img/escudos/intermilan.webp"
  },
  {
    "id": 12,
    "grupo": "F",
    "local": "Ulsan",
    "visitante": "Mamelodi Sundowns",
    "fecha": "17 junio",
    "hora": "18:00",
    "ciudad": "Orlando",
    "escudoLocal": "./img/escudos/ulsan.webp",
    "escudoVisitante": "./img/escudos/mamelodi.webp"
  },
  {
    "id": 13,
    "grupo": "G",
    "local": "Manchester City",
    "visitante": "Wydad Casablanca",
    "fecha": "18 junio",
    "hora": "12:00",
    "ciudad": "Filadelfia",
    "escudoLocal": "./img/escudos/manchestercity.webp",
    "escudoVisitante": "./img/escudos/wydad.webp"
  },
  {
    "id": 14,
    "grupo": "H",
    "local": "Real Madrid",
    "visitante": "Al Hilal",
    "fecha": "18 junio",
    "hora": "15:00",
    "ciudad": "Miami",
    "escudoLocal": "./img/escudos/realmadrid.webp",
    "escudoVisitante": "./img/escudos/alhilal.webp"
  },
  {
    "id": 15,
    "grupo": "H",
    "local": "Pachuca",
    "visitante": "Salzburgo",
    "fecha": "18 junio",
    "hora": "18:00",
    "ciudad": "Cincinnati",
    "escudoLocal": "./img/escudos/pachuca.webp",
    "escudoVisitante": "./img/escudos/salzburg.webp"
  },
  {
    "id": 16,
    "grupo": "G",
    "local": "Al Ain",
    "visitante": "Juventus",
    "fecha": "18 junio",
    "hora": "21:00",
    "ciudad": "Washington D.C.",
    "escudoLocal": "./img/escudos/alain.webp",
    "escudoVisitante": "./img/escudos/juventus.webp"
  },
  {
    "id": 17,
    "grupo": "A",
    "local": "Palmeiras",
    "visitante": "Al Ahly",
    "fecha": "19 junio",
    "hora": "12:00",
    "ciudad": "Nueva York-Nueva Jersey",
    "escudoLocal": "./img/escudos/palmeiras.webp",
    "escudoVisitante": "./img/escudos/alahly.webp"
  },
  {
    "id": 18,
    "grupo": "B",
    "local": "Seattle Sounders",
    "visitante": "Atlético de Madrid",
    "fecha": "19 junio",
    "hora": "15:00",
    "ciudad": "Seattle",
    "escudoLocal": "./img/escudos/seattle.webp",
    "escudoVisitante": "./img/escudos/atleticomadrid.webp"
  },
  {
    "id": 19,
    "grupo": "A",
    "local": "Inter Miami",
    "visitante": "Porto",
    "fecha": "19 junio",
    "hora": "15:00",
    "ciudad": "Atlanta",
    "escudoLocal": "./img/escudos/intermiami.webp",
    "escudoVisitante": "./img/escudos/porto.webp"
  },
  {
    "id": 20,
    "grupo": "B",
    "local": "PSG",
    "visitante": "Botafogo",
    "fecha": "19 junio",
    "hora": "18:00",
    "ciudad": "Los Ángeles",
    "escudoLocal": "./img/escudos/psg.webp",
    "escudoVisitante": "./img/escudos/botafogo.webp"
  },
  {
    "id": 21,
    "grupo": "D",
    "local": "Flamengo",
    "visitante": "Chelsea",
    "fecha": "20 junio",
    "hora": "14:00",
    "ciudad": "Filadelfia",
    "escudoLocal": "./img/escudos/flamengo.webp",
    "escudoVisitante": "./img/escudos/chelsea.webp"
  },
  {
    "id": 22,
    "grupo": "C",
    "local": "Benfica",
    "visitante": "Auckland City",
    "fecha": "20 junio",
    "hora": "12:00",
    "ciudad": "Orlando",
    "escudoLocal": "./img/escudos/benfica.webp",
    "escudoVisitante": "./img/escudos/aucklandcity.webp"
  },
  {
    "id": 23,
    "grupo": "D",
    "local": "León",
    "visitante": "Esperance Sportive",
    "fecha": "20 junio",
    "hora": "17:00",
    "ciudad": "Nashville",
    "escudoLocal": "./img/escudos/leon.webp",
    "escudoVisitante": "./img/escudos/esperance.webp"
  },
  {
    "id": 24,
    "grupo": "C",
    "local": "Bayern Múnich",
    "visitante": "Boca Júniors",
    "fecha": "20 junio",
    "hora": "21:00",
    "ciudad": "Miami",
    "escudoLocal": "./img/escudos/bayern.webp",
    "escudoVisitante": "./img/escudos/boca.webp"
  },
  {
    "id": 25,
    "grupo": "E",
    "local": "Inter de Milán",
    "visitante": "Urawa Red Diamonds",
    "fecha": "21 junio",
    "hora": "12:00",
    "ciudad": "Seattle",
    "escudoLocal": "./img/escudos/intermilan.webp",
    "escudoVisitante": "./img/escudos/urawa.webp"
  },
  {
    "id": 26,
    "grupo": "F",
    "local": "Mamelodi Sundowns",
    "visitante": "Borussia Dortmund",
    "fecha": "21 junio",
    "hora": "12:00",
    "ciudad": "Cincinnati",
    "escudoLocal": "./img/escudos/mamelodi.webp",
    "escudoVisitante": "./img/escudos/borussia.webp"
  },
  {
    "id": 27,
    "grupo": "E",
    "local": "River Plate",
    "visitante": "Monterrey",
    "fecha": "21 junio",
    "hora": "18:00",
    "ciudad": "Los Ángeles",
    "escudoLocal": "./img/escudos/river.webp",
    "escudoVisitante": "./img/escudos/monterrey.webp"
  },
  {
    "id": 28,
    "grupo": "F",
    "local": "Fluminense",
    "visitante": "Ulsan",
    "fecha": "21 junio",
    "hora": "18:00",
    "ciudad": "Nueva York-Nueva Jersey",
    "escudoLocal": "./img/escudos/fluminense.webp",
    "escudoVisitante": "./img/escudos/ulsan.webp"
  },
  {
    "id": 29,
    "grupo": "G",
    "local": "Juventus",
    "visitante": "Wydad Casablanca",
    "fecha": "22 junio",
    "hora": "12:00",
    "ciudad": "Filadelfia",
    "escudoLocal": "./img/escudos/juventus.webp",
    "escudoVisitante": "./img/escudos/wydad.webp"
  },
  {
    "id": 30,
    "grupo": "H",
    "local": "Real Madrid",
    "visitante": "Pachuca",
    "fecha": "22 junio",
    "hora": "15:00",
    "ciudad": "Charlotte",
    "escudoLocal": "./img/escudos/realmadrid.webp",
    "escudoVisitante": "./img/escudos/pachuca.webp"
  },
  {
    "id": 31,
    "grupo": "H",
    "local": "Salzburgo",
    "visitante": "Al Hilal",
    "fecha": "22 junio",
    "hora": "18:00",
    "ciudad": "Washington D.C.",
    "escudoLocal": "./img/escudos/salzburg.webp",
    "escudoVisitante": "./img/escudos/alhilal.webp"
  },
  {
    "id": 32,
    "grupo": "G",
    "local": "Manchester City",
    "visitante": "Al Ain",
    "fecha": "22 junio",
    "hora": "21:00",
    "ciudad": "Atlanta",
    "escudoLocal": "./img/escudos/manchestercity.webp",
    "escudoVisitante": "./img/escudos/alain.webp"
  },
  {
    "id": 33,
    "grupo": "B",
    "local": "Atlético de Madrid",
    "visitante": "Botafogo",
    "fecha": "23 junio",
    "hora": "12:00",
    "ciudad": "Los Ángeles",
    "escudoLocal": "./img/escudos/atleticomadrid.webp",
    "escudoVisitante": "./img/escudos/botafogo.webp"
  },
  {
    "id": 34,
    "grupo": "B",
    "local": "Seattle Sounders",
    "visitante": "PSG",
    "fecha": "23 junio",
    "hora": "12:00",
    "ciudad": "Seattle",
    "escudoLocal": "./img/escudos/seattle.webp",
    "escudoVisitante": "./img/escudos/psg.webp"
  },
  {
    "id": 35,
    "grupo": "A",
    "local": "Inter Miami",
    "visitante": "Palmeiras",
    "fecha": "23 junio",
    "hora": "21:00",
    "ciudad": "Miami",
    "escudoLocal": "./img/escudos/intermiami.webp",
    "escudoVisitante": "./img/escudos/palmeiras.webp"
  },
  {
    "id": 36,
    "grupo": "A",
    "local": "Oporto",
    "visitante": "Al Ahly",
    "fecha": "23 junio",
    "hora": "21:00",
    "ciudad": "Nueva York-Nueva Jersey",
    "escudoLocal": "./img/escudos/porto.webp",
    "escudoVisitante": "./img/escudos/alahly.webp"
  },
  {
    "id": 37,
    "grupo": "C",
    "local": "Boca Júniors",
    "visitante": "Auckland City",
    "fecha": "24 junio",
    "hora": "12:00",
    "ciudad": "Orlando",
    "escudoLocal": "./img/escudos/boca.webp",
    "escudoVisitante": "./img/escudos/aucklandcity.webp"
  },
  {
    "id": 38,
    "grupo": "D",
    "local": "Esperance Sportive",
    "visitante": "Chelsea",
    "fecha": "24 junio",
    "hora": "15:00",
    "ciudad": "Nashville",
    "escudoLocal": "./img/escudos/esperance.webp",
    "escudoVisitante": "./img/escudos/chelsea.webp"
  },
  {
    "id": 39,
    "grupo": "C",
    "local": "Benfica",
    "visitante": "Bayern Múnich",
    "fecha": "24 junio",
    "hora": "18:00",
    "ciudad": "Cincinnati",
    "escudoLocal": "./img/escudos/benfica.webp",
    "escudoVisitante": "./img/escudos/bayern.webp"
  },
  {
    "id": 40,
    "grupo": "D",
    "local": "León",
    "visitante": "Flamengo",
    "fecha": "24 junio",
    "hora": "18:00",
    "ciudad": "Filadelfia",
    "escudoLocal": "./img/escudos/leon.webp",
    "escudoVisitante": "./img/escudos/flamengo.webp"
  },
  {
    "id": 41,
    "grupo": "E",
    "local": "Inter de Milán",
    "visitante": "River Plate",
    "fecha": "25 junio",
    "hora": "18:00",
    "ciudad": "Seattle",
    "escudoLocal": "./img/escudos/intermilan.webp",
    "escudoVisitante": "./img/escudos/river.webp"
  },
  {
    "id": 42,
    "grupo": "E",
    "local": "Urawa Red Diamonds",
    "visitante": "Monterrey",
    "fecha": "25 junio",
    "hora": "18:00",
    "ciudad": "Los Ángeles",
    "escudoLocal": "./img/escudos/urawa.webp",
    "escudoVisitante": "./img/escudos/monterrey.webp"
  },
  {
    "id": 43,
    "grupo": "F",
    "local": "Mamelodi Sundowns",
    "visitante": "Fluminense",
    "fecha": "25 junio",
    "hora": "15:00",
    "ciudad": "Miami",
    "escudoLocal": "./img/escudos/mamelodi.webp",
    "escudoVisitante": "./img/escudos/fluminense.webp"
  },
  {
    "id": 44,
    "grupo": "F",
    "local": "Borussia Dortmund",
    "visitante": "Ulsan",
    "fecha": "25 junio",
    "hora": "15:00",
    "ciudad": "Cincinnati",
    "escudoLocal": "./img/escudos/borussia.webp",
    "escudoVisitante": "./img/escudos/ulsan.webp"
  },
  {
    "id": 45,
    "grupo": "G",
    "local": "Juventus",
    "visitante": "Manchester City",
    "fecha": "26 junio",
    "hora": "15:00",
    "ciudad": "Orlando",
    "escudoLocal": "./img/escudos/juventus.webp",
    "escudoVisitante": "./img/escudos/manchestercity.webp"
  },
  {
    "id": 46,
    "grupo": "G",
    "local": "Wydad Casablanca",
    "visitante": "Al Ain",
    "fecha": "26 junio",
    "hora": "15:00",
    "ciudad": "Washington D.C.",
    "escudoLocal": "./img/escudos/wydad.webp",
    "escudoVisitante": "./img/escudos/alain.webp"
  },
  {
    "id": 47,
    "grupo": "H",
    "local": "Salzburgo",
    "visitante": "Real Madrid",
    "fecha": "26 junio",
    "hora": "21:00",
    "ciudad": "Filadelfia",
    "escudoLocal": "./img/escudos/salzburg.webp",
    "escudoVisitante": "./img/escudos/realmadrid.webp"
  },
  {
    "id": 48,
    "grupo": "H",
    "local": "Al Hilal",
    "visitante": "Pachuca",
    "fecha": "26 junio",
    "hora": "20:00",
    "ciudad": "Nashville",
    "escudoLocal": "./img/escudos/alahly.webp",
    "escudoVisitante": "./img/escudos/pachuca.webp"
  }
] 
